apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger
  labels:
    app: messenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messenger
  template:
    metadata:
      labels:
        app: messenger
    spec:
      containers:
      - name: messenger
        image: npalm/hello-mesh-messenger
        imagePullPolicy: Always
        ports:
          - name: http
            protocol: TCP
            containerPort: 3000
        livenessProbe:
          httpGet:
            port: http
            path: /
        readinessProbe:
          httpGet:
            port: http
            path: /
        resources:
          requests:
            memory: 50Mi
            cpu: 100m
          limits:
            memory: 500Mi
            cpu: 500m
        env:
        - name: MESSAGE
          value: "MESSAGE_TEXT"

---
apiVersion: v1
kind: Service
metadata:
  name: messenger
  labels:
    app: messenger
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: http
  selector:
    app: messenger


